services:
  - type: web
    name: shipping-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://shipping-frontend-rho.vercel.app,http://localhost:3000
      - key: MONGO_URI
        value: mongodb+srv://shippinguser:5IYOL8jte8hA4Cxf@shipping-db.6e3wp9f.mongodb.net/?appName=shipping-db
    healthCheckPath: /api/health
    autoDeploy: true
